// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFt8vgBl1DQtDO4WMBiGQ5s-9-z7ZgenQ',
    appId: '1:390141766071:web:8b6a0e983c13e0fcec6032',
    messagingSenderId: '390141766071',
    projectId: 'flutter-test-10c8a',
    authDomain: 'flutter-test-10c8a.firebaseapp.com',
    storageBucket: 'flutter-test-10c8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAet1kXO7rQuikByeiq5jgRqu98wuwMA7E',
    appId: '1:390141766071:android:3f2ef25f601955b0ec6032',
    messagingSenderId: '390141766071',
    projectId: 'flutter-test-10c8a',
    storageBucket: 'flutter-test-10c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJQGxsrSTIMVnSXBluEqReLnCbjdyH16U',
    appId: '1:390141766071:ios:8762ea36a880220eec6032',
    messagingSenderId: '390141766071',
    projectId: 'flutter-test-10c8a',
    storageBucket: 'flutter-test-10c8a.appspot.com',
    iosBundleId: 'com.example.crudeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJQGxsrSTIMVnSXBluEqReLnCbjdyH16U',
    appId: '1:390141766071:ios:8762ea36a880220eec6032',
    messagingSenderId: '390141766071',
    projectId: 'flutter-test-10c8a',
    storageBucket: 'flutter-test-10c8a.appspot.com',
    iosBundleId: 'com.example.crudeFirebase',
  );
}
